workflow:
  IS_DRY_RUN: false  # Est-ce un dry_run (sans mise a jour des bases)
  TODO:
    - IS_MAINT_LR_0000000 # Maintenance sur la base LR
    - IS_ACTION_FROM_KEY0 # déplacement des photos tagger par TAG_ACTION_GO_RAPPROCHEMENT et Context.COLLECTIONS
    - IS_PURGE_ACTION_000 # remove les tag [action] des photos (TAG_ACTION_GO_RAPPROCHEMENT et Context.COLLECTIONS)
    - IS_TAG_DEL_00000000 # purge des tag liée au [Maitre] diffrent des tag crée par IS_TAG_CR_000000000 (par ex les TAG_REPSWEEP++ et TAG_RAPPROCHEMENT++)
    - IS_TAG_CR_000000000 # creation du tag [Maitre] (TAG_ORG) , des tag [Projet] (TAG_RAPPROCHEMENT , TAG_REPSWEEP) et [action] (TAG_ACTION_GO_RAPPROCHEMENT et Context.COLLECTIONS)
    - IS_RETAG_RED_000000 # topper A 'RED' les photos NEW et deTopper A 'RED' les repertoire;
    - IS_WRK_REJET_000000 # ranger [les repertoire rejet et les les photo tagger rejeter] dans les repertoires rejet ou le 99-rejet (pour suppression)
    - IS_UNZIP_REP_PHOTO0 # extraire les ZIP dans les repertoire rejet
    - IS_WRK_REP_PHOTO_00 # analyse des repertoires en function des regles => analFonctionRep
    - IS_RGP_NEW_00000000 # regrouper les photo New par temps adherence
    - IS_LST_RAPP_NEW_REP # lister Les Rapprochement Avec Les Repertoires Photo (regrouper les photo New avec la photothèque par temps adherence) => grpPhotosRapprocher
    - IS_TAG_RAPP_NEW_REP # grpPhotosRapprocher => mise En Place Des TAG_RAPPROCHEMENT++ possible entre les new et la phototheque
    - IS_PURGE_FOLDER_000 # purgeDesRepertoireVide50Phototheque() (local) et purgeDesRepertoireVide00NEW() (reseau)
    - IS_TAG_CTRL_REP_000 # analFonctionRep => appliquer des tag TAG_REPSWEEP++ sur les photo et mise a 'RED' de repertoire en fonction de analFonctionRep.getListOfretourValRepertoire()
    - IS_EXEC_FONC_REP_00 # analFonctionRep => Renommage des repertoire via POP UP.
  NOTTODO:
    - IS_SVG_LRCONFIG_000 # sauvegarde du la config LR sur le reseau.
    - IS_RSYNC_BIB_000000 # sauvegarde des photos sur le reseau.
    - EMPTY
paramControleRepertoire:
  listControleRepertoire:
    - starValue
    - nbSelectionner
    - nbNonSelectionner
    - nbphotoapurger
    - nbelements
    - limitemaxfolder
paramElementsRejet:
  arrayNomSubdirectoryRejet:
    - rejet
    - dark
    - offset
    - flat
    - brut
    - jpg
  arrayNomFileRejet:
    - jpg
    - tif
    - dng
    - jpeg
    - arw
    - mp4
    - thm
    - png
    - mts
  arrayNomFileRejetSup:
    - txt
    - tmp
    - pto
  extFileRejet: rejet
paramTriNew:
  repertoire50NEW: "D:\\50_Phototheque\\05-A_Ranger\\@New\\"
  repertoireBazar: "D:\\50_Phototheque\\05-A_Ranger\\@New\\Bazar\\"
  repertoireKidz: "D:\\50_Phototheque\\70-Kidz__\\"
  thresholdNew: 10
  tempsAdherence: "90 minutes"
  listeModelKidz:
    - Kidizoom camera
    - KidiSecrets Selfie Music
repFonctionnel:
  repertoireDestZip: "D:\\95_Boite_a_outils\\LigthroomConfigSauve\\ligthroomSauve-%num%.zip"
  repertoireRoamingAdobeLightroom: "C:\\Users\\professorX\\AppData\\Roaming\\Adobe\\Lightroom"
  repertoire50Phototheque: "D:\\50_Phototheque\\"
  repertoire00NEW: "P:\\00_NEW\\"
  repertoireCatalog: "D:\\70_Catalogs\\70_Catalog_Phototheque"
  catalogLrcat: "70_Catalog_Phototheque-2.lrcat"
  nbRotateRepertoireDestZip: "5"
  rsyncexclude:
    - "*\\System Volume Information\\*"
    - "*\\$RECYCLE.BIN\\*"
    - "*\\$Recycle.Bin\\*"
    - "*\\RECYCLER\\*"
    - "*\\RECYCLED\\*"
    - "*\\desktop.ini"
    - "*\\thumbs.db"
    - "*.lrdata"
    - "*\\log\\*"
  repertoiresyncsource:
    - "D:\\50_Phototheque"
    - "D:\\70_Catalogs"
    - "D:\\80_Logiciel_Windows"
    - "D:\\95_Boite_a_outils"
  repertoiresyncdest: "\\\\LEGION-2\\20-photo\\"
  syncdestmouchard: photoOrganizeLastSync.txt
  syncAmountDaysBetween: 10
arrayRepertoirePhoto:
  - repertoire: '01-Cataloque_Photo\\!!Collections\\##Autoconstruction 03-05 j'
    nomunique: Autoconstruction
    uniteDeJour: 1
    nbMaxParUniteDeJour: 5
    ratioStarMax:
      - 25
      - 12
      - 5
      - 2
      - 1
    zoneValeurAdmise:
      - '£DATE£'
      - '@10_Action@'
      - '@10_Piece@'
      - '@10_Chantier@'
    rapprochermentNewOk: false
  - repertoire: '01-Cataloque_Photo\##Events 10-15 j'
    nomunique: Events
    uniteDeJour: 1
    nbMaxParUniteDeJour: 15
    ratioStarMax:
      - 25
      - 12
      - 5
      - 2
      - 1
    zoneValeurAdmise:
      - '£DATE£'
      - '@00_EVENT@'
      - '@00_WHERE@'
      - '@00_WHAT@|@00_WHO@'
    rapprochermentNewOk: true
  - repertoire: '01-Cataloque_Photo\##Holidays 20-30 sem'
    nomunique: Holidays
    uniteDeJour: 3
    nbMaxParUniteDeJour: 21
    ratioStarMax:
      - 25
      - 12
      - 5
      - 2
      - 1
    zoneValeurAdmise:
      - '£DATE£'
      - '@00_EVENT@'
      - '@00_WHERE@'
      - '@00_WHAT@|@00_WHO@'
    rapprochermentNewOk: true
  - repertoire: '01-Cataloque_Photo\##Shooting 03-05 j'
    nomunique: Shooting
    uniteDeJour: 1
    nbMaxParUniteDeJour: 2
    ratioStarMax:
      - 25
      - 12
      - 5
      - 2
      - 1
    zoneValeurAdmise:
      - '£DATE£'
      - '@00_PHOTOGRAPHY@'
      - '@00_WHERE@'
      - '@00_WHAT@|@00_WHO@'
    rapprochermentNewOk: true
  - repertoire: '99-Rejet'
    nomunique: Rejet
    uniteDeJour: 1
    nbMaxParUniteDeJour: 999
    ratioStarMax:
      - 0
      - 0
      - 0
      - 0
      - 0
    zoneValeurAdmise:
      - '£DATE£'
    rapprochermentNewOk: false
  - repertoire: '01-Cataloque_Photo\!!Collections\##Sauvegarde 999 j'
    nomunique: Sauvegarde
    uniteDeJour: 1
    nbMaxParUniteDeJour: 999
    ratioStarMax:
      - 100
      - 100
      - 100
      - 100
      - 100
    zoneValeurAdmise:
      - '£DATE£'
    rapprochermentNewOk: false