version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8999:8099"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3900:3000"
    environment:
      - REACT_APP_API_URL=http://backend-service:8099/api
    depends_on:
      - backend
    networks:
      - assistant-photo

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5932:5432"
    networks:
      - assistant-photo

networks:
  assistant-photo: