version: '3.8'
name: assistantphoto
services:
    assistantPhoto:
        image: maliciamrg/assistantphoto:0.0.1-SNAPSHOT
        ports:
            - 8080:8080
        container_name: assistantPhoto
        volumes:
            - '/Photo/lrcat:/Lrcat'
            - '/Photo/50-Phototheque:/Phototheque'
    whoami:
        image: traefik/whoami
        ports:
            - 8787:80