version: '3.8'
name: photoorganize
services:
    queryLrcatApi:
        image: maliciamrg/querylrcatapi:0.0.1-SNAPSHOT
        ports:
            - 8091:8091
        container_name: queryLrcatApi
        volumes:
            - '/Photo/lrcat:/Lrcat'
    photoOrganize_Front:
        image: maliciamrg/photoorganize_front:0.1.0
        ports:
            - 3000:3000
        container_name: photoOrganize_Front
    photoOrganize_Back:
        image: maliciamrg/photoorganize_back:1.0
        ports:
            - 8090:8090
        container_name: photoOrganize_Back
        volumes:
            - '/Photo/50-Phototheque:/Phototheque'