version: '3.8'
services:
    assistant_photo_back:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8099:8099
        volumes:
            - '/Photo/lrcat:/Lrcat'
            - '/Photo/50-Phototheque:/Phototheque'