spring:
  application:
    name: '@project.artifactId@'
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8090
application:
  version: '@project.version@'
  ipWan: 192.212.5.200
  allowed_extensions:
    - jpg
    - tif
    - tiff
    - dng
    - jpeg
    - arw
    - mp4
    - png
    - mts
    - mov
    - avi
    - m2ts
    - 3gp
    - m4v
    - mpg
    - psd
    - bmp
    - gif
    - tiff_original
  exclude_subdirectory_reject:
    - rejet
    - dark
    - offset
    - flat
    - brut
    - image
    - jpg
