spring:
  application:
    name: photo-organize-infrastructure
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
application:
  lightroomdbpath: src/test/ressources/database/70_Catalog_Phototheque-2-v12.lrcat

