assistant:
  dryRun: true
  rootPath: ./src/test/resources/
  groupPhoto:
    ecartEnMinutes: 20
    photoMin: 5
  repertoireOfType:
    - seanceType: all_in
      repertoire:
        - path: "00-CheckIn"
          description: "Main check-in folder"
        - path: "00-CheckIn-2"
          description: "Backup check-in folder"
    - seanceType: assistant_work
      repertoire:
        - path: "10-Assistant_work"
          description: "Work folder for the Assistant"
    - seanceType: Events
      repertoire:
        - path: "50-Phototheque\\##Events 10-15 j"
          description: "Events photographs"
    - seanceType: Holidays
      repertoire:
        - path: "50-Phototheque\\##Holidays 20-30 sem"
          description: "Holiday photographs"
    - seanceType: Shooting
      repertoire:
        - path: "50-Phototheque\\##Shooting 03-05 j"
          description: "Shooting session photographs"
    - seanceType: Rejet
      repertoire:
        - path: "99-Rejet"
          description: "Rejected items"
    - seanceType: Sauvegarde
      repertoire:
        - path: "50-Phototheque\\#Sauvegarde 999 j"
          description: "Backup photographs"