workflow:
  IS_DRY_RUN: false  # Est-ce un dry_run (sans mise a jour des bases)
  TODO:
#    - IS_WRK_REJET_000000 # ranger [les repertoire rejet et les les photo tagger rejeter] dans les repertoires rejet ou le 99-rejet (pour suppression)
#    - IS_SYNCR_LR_0000000 # Synchronise les repertoire et fichiers physique avec la base LR
#  NOTTODO:
    - IS_SYNCR_LR_0000000 # Synchronise les repertoire et fichiers physique avec la base LR
    - IS_MAINT_LR_0000000 # Maintenance sur la base LR
    - IS_PURGE_FOLDER_000 # purgeDesRepertoireVide50Phototheque() (local) et purgeDesRepertoireVide00NEW() (reseau)
    - IS_WRK_REJET_000000 # ranger [les repertoire rejet et les les photo tagger rejeter] dans les repertoires rejet ou le 99-rejet (pour suppression)
    - IS_ACTION_FROM_KEY0 # (raprochement) déplacement des photos tagger par TAG_ACTION_GO_RAPPROCHEMENT et Context.COLLECTIONS
    - IS_PURGE_ACTION_000 # (raprochement) remove les tag [action] des photos (TAG_ACTION_GO_RAPPROCHEMENT et Context.COLLECTIONS)
    - IS_TAG_DEL_00000000 # (raprochement) purge des tag liée au [Maitre] diffrent des tag crée par IS_TAG_CR_000000000 (par ex les TAG_REPSWEEP++ et TAG_RAPPROCHEMENT++)
    - IS_TAG_CR_000000000 # (raprochement) creation du tag [Maitre] (TAG_ORG) , des tag [Projet] (TAG_RAPPROCHEMENT , TAG_REPSWEEP) et [action] (TAG_ACTION_GO_RAPPROCHEMENT et Context.COLLECTIONS)
    - IS_RETAG_RED_000000 # (raprochement) topper A 'RED' les photos NEW et deTopper A 'RED' les repertoire;
    - IS_RGP_NEW_00000000 # (raprochement) regrouper les photo New par temps adherence
    - IS_LST_RAPP_NEW_REP # (raprochement) lister Les Rapprochement Avec Les Repertoires Photo (regrouper les photo New avec la photothèque par temps adherence) => grpPhotosRapprocher
    - IS_TAG_RAPP_NEW_REP # (raprochement) grpPhotosRapprocher => mise En Place Des TAG_RAPPROCHEMENT++ possible entre les new et la phototheque
    - IS_RETAG_GREEN_0000 # (whatsapp) topper A 'GREEN' les photos NEW et deTopper A 'GREEN' les repertoire;
    - IS_WRK_REP_PHOTO_00 # (analFonctionRep) analyse des repertoires en function des regles => analFonctionRep
    - IS_TAG_CTRL_REP_000 # (analFonctionRep) => appliquer des tag TAG_REPSWEEP++ sur les photo et mise a 'RED' de repertoire en fonction de analFonctionRep.getListOfretourValRepertoire()
    - IS_EXEC_FONC_REP_00 # (analFonctionRep) => Renommage des repertoire via POP UP.
  NOTTODO:
    - IS_UNZIP_REP_PHOTO0 # extraire les ZIP dans les repertoire rejet
    - IS_SVG_LRCONFIG_000 # sauvegarde du la config LR sur le reseau.
    - EMPTY
    - IS_RSYNC_BIB_000000 # sauvegarde des photos sur le reseau.
    - IS_FORCE_SVG_000000 # force time to sauvegarde
dataApplication:
  applicationToClose: "taskkill /f /im Lightroom.exe"
#    - "taskkill /f /im dynamiclinkmediaserver.exe"
#    - "rmdir /s /q C:\Users\cleme\AppData\Local\Adobe\Lightroom\Caches\Video"
paramControleRepertoire:
  listControleRepertoire:
    - starValue
    - nbSelectionner
    - nbNonSelectionner
    - nbphotoapurger
    - nbelements
    - limitemaxfolder
extensionsUseFile:
    - jpg
    - tif
    - tiff
    - dng
    - jpeg
    - arw
    - mp4
    - png
    - mts
    - mov
    - avi
    - m2ts
    - 3gp
    - m4v
    - mpg
    - psd
    - bmp
    - gif
    - tiff_original
paramElementsRejet:
  arrayNomSubdirectoryRejet:
    - rejet
    - dark
    - offset
    - flat
    - brut
    - image
    - jpg
  arrayExtensionFileRejetSup:
    - txt
    - tmp
    - pto
    - xmp
    - thm
    - lrv
    - pxd
    - lrbak
  extFileRejet: rejet
paramTriNew:
  repertoire50NEW: "C:\\Users\\cleme\\Desktop\\@New\\"
  repertoireBazar: "C:\\Users\\cleme\\Desktop\\@New\\Bazar\\"
  repertoireKidz: "Y:\\70-Kidz__\\"
  thresholdNew: 10
  tempsAdherence: "90 minutes"
  listeModelKidz:
    - Kidizoom camera
    - KidiSecrets Selfie Music
repFonctionnel:
  repertoireDestZip: "Y:\\95_Boite_a_outils\\LigthroomConfigSauve\\ligthroomSauve-%num%.zip"
  repertoireRoamingAdobeLightroom: "C:\\Users\\cleme\\AppData\\Roaming\\Adobe\\Lightroom"
  repertoire50Phototheque: "Y:\\50-Phototheque\\"
  repertoire00NEW: "Y:\\00-CheckIn\\"
  repertoireCatalog: "C:\\Users\\cleme\\Desktop\\50-Phototheque\\70_Catalog_Phototheque"
  catalogLrcat: "70_Catalog_Phototheque-2-v12.lrcat"
  nbRotateRepertoireDestZip: "5"
  rsyncexclude:
    - "*\\System Volume Information\\*"
    - "*\\$RECYCLE.BIN\\*"
    - "*\\$Recycle.Bin\\*"
    - "*\\RECYCLER\\*"
    - "*\\RECYCLED\\*"
    - "*\\desktop.ini"
    - "*\\thumbs.db"
    - "*.lrdata"
    - "*.lrcat-*"
    - "*\\log\\*"
  repertoiresyncsource:
    - "D:\\50-Phototheque\\05-A_Ranger"
    - "C:\\Users\\cleme\\Desktop\\50-Phototheque\\70_Catalog_Phototheque"
  repertoiresyncdest: "Y:\\99_Sauvegarde\\"
  syncdestmouchard: photoOrganizeLastSync.txt
  syncAmountDaysBetween: 15
arrayRepertoirePhoto:
  - repertoire: '01-Cataloque_Photo\\!!Collections\\##Autoconstruction 03-05 j'
    nomunique: Autoconstruction
    uniteDeJour: 1
    nbMaxParUniteDeJour: 5
    ratioStarMax:
      - 25
      - 12
      - 5
      - 2
      - 1
    zoneValeurAdmise:
      - '£DATE£'
      - '@10_Action@'
      - '@10_Piece@'
      - '@10_Chantier@'
    rapprochermentNewOk: false
  - repertoire: '01-Cataloque_Photo\##Events 10-15 j'
    nomunique: Events
    uniteDeJour: 1
    nbMaxParUniteDeJour: 15
    ratioStarMax:
      - 25
      - 12
      - 5
      - 2
      - 1
    zoneValeurAdmise:
      - '£DATE£'
      - '@00_EVENT@'
      - '@00_WHERE@'
      - '@00_WHAT@|@00_WHO@'
    rapprochermentNewOk: true
  - repertoire: '01-Cataloque_Photo\##Holidays 20-30 sem'
    nomunique: Holidays
    uniteDeJour: 7
    nbMaxParUniteDeJour: 30
    ratioStarMax:
      - 25
      - 12
      - 5
      - 2
      - 1
    zoneValeurAdmise:
      - '£DATE£'
      - '@00_EVENT@'
      - '@00_WHERE@'
      - '@00_WHAT@|@00_WHO@'
    rapprochermentNewOk: true
  - repertoire: '01-Cataloque_Photo\##Shooting 03-05 j'
    nomunique: Shooting
    uniteDeJour: 1
    nbMaxParUniteDeJour: 5
    ratioStarMax:
      - 25
      - 12
      - 5
      - 2
      - 1
    zoneValeurAdmise:
      - '£DATE£'
      - '@00_PHOTOGRAPHY@'
      - '@00_WHERE@'
      - '@00_WHAT@|@00_WHO@'
    rapprochermentNewOk: true
  - repertoire: '99-Rejet'
    nomunique: Rejet
    uniteDeJour: 1
    nbMaxParUniteDeJour: 999
    ratioStarMax:
      - 0
      - 0
      - 0
      - 0
      - 0
    zoneValeurAdmise:
      - '£DATE£'
    rapprochermentNewOk: false
  - repertoire: '01-Cataloque_Photo\!!Collections\##Sauvegarde 999 j'
    nomunique: Sauvegarde
    uniteDeJour: 1
    nbMaxParUniteDeJour: 999
    ratioStarMax:
      - 100
      - 100
      - 100
      - 100
      - 100
    zoneValeurAdmise:
      - '£DATE£'
    rapprochermentNewOk: false